version: '3.4'

services:
  proyecta_app_react_dev:
    image: proyecta_app_react
    container_name: proyecta_app_react_dev
    build:
      context: .
    ports:
      - "3001:80"
    networks:
      - proyecta-network

networks:
  proyecta-network:
    external: true
