version: '3.4'

services:
  app:
    image: proyecta_react_prod
    container_name: 'proyecta_react_prod'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${PROYECTA_REACT_API_URL}
    #volumes:
    #  - './:/usr/share/nginx/html'
    networks:
      - proyecta_network

networks:
  proyecta_network:
