# Development Dockerfile
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the app's source code from the host to the image filesystem
COPY . .

# Set environment variables for the build
ARG API_URL
ENV REACT_APP_API_URL=$API_URL
RUN echo "REACT_APP_API_URL is '${REACT_APP_API_URL}'"

# Expose the port to the host
EXPOSE 3000

# Start development server
CMD ["npm", "start"]
