# Stage 1: Build React app
FROM node:18-alpine AS development
WORKDIR /app
EXPOSE 3000
ENV NODE_ENV development

# Add tools
RUN apk --no-cache add curl

# RUN
COPY package.json /app
COPY package-lock.json /app
RUN npm ci

COPY . .

CMD npm start
